from __future__ import annotations

import hashlib
import json
import os
from typing import Dict, List, Any
from urllib.parse import urlparse

from recon_cli.pipeline.context import PipelineContext
from recon_cli.pipeline.stage_base import Stage


class POCGeneratorStage(Stage):
    """
    Automated Proof-of-Concept (POC) Generator.
    Generates standalone Python reproduction scripts for confirmed findings.
    """
    name = "poc_generator"

    def is_enabled(self, context: PipelineContext) -> bool:
        return bool(getattr(context.runtime_config, "enable_poc_generator", True))

    def execute(self, context: PipelineContext) -> None:
        findings = [r for r in context.get_results() if r.get("type") == "finding"]
        confirmed = [f for f in findings if f.get("confidence_label") == "verified" or int(f.get("score", 0)) >= 85]

        if not confirmed:
            context.logger.info("No high-confidence findings found for POC generation")
            return

        poc_dir = context.record.paths.ensure_subdir("pocs")
        generated_count = 0

        for finding in confirmed:
            script_content = self._generate_python_poc(finding)
            if script_content:
                f_type = finding.get("finding_type", "vuln")
                f_hash = hashlib.md5(str(finding.get("url", "")).encode()).hexdigest()[:6]
                filename = f"poc_{f_type}_{f_hash}.py"
                
                poc_path = poc_dir / filename
                poc_path.write_text(script_content)
                generated_count += 1
                
                # Update finding with POC path
                finding["poc_path"] = str(poc_path)
                context.logger.info("Generated POC script: %s", filename)

        context.logger.info("Successfully generated %d POC scripts in %s", generated_count, poc_dir)

    def _generate_python_poc(self, finding: Dict[str, Any]) -> str | None:
        url = finding.get("url")
        if not url: return None
        
        f_type = finding.get("finding_type", "vulnerability")
        desc = finding.get("description", "Reproduction script")
        
        # Template for the Python POC
        template = f'''"""
POC for {f_type}
Description: {desc}
Generated by ReconnV2
"""

import requests
import sys

def exploit():
    url = "{url}"
    print(f"[*] Targeting: {{url}}")
    
    headers = {{
        "User-Agent": "Mozilla/5.0 (ReconnV2 POC Generator)",
    }}
    
    try:
        # Replaying the triggering request
        # Note: In a real scenario, you might need to add specific payloads or cookies
        response = requests.get(url, headers=headers, verify=False, timeout=15)
        
        print(f"[+] Status Code: {{response.status_code}}")
        print(f"[+] Response Length: {{len(response.text)}}")
        
        # Heuristic check for success
        print("[*] Manual verification required to confirm impact.")
        
    except Exception as e:
        print(f"[-] Error: {{e}}")

if __name__ == "__main__":
    exploit()
'''
        return template
