from __future__ import annotations

import hashlib
import json
import os
import asyncio
from typing import Dict, List, Any, Optional
from urllib.parse import urlparse

from recon_cli.pipeline.context import PipelineContext
from recon_cli.pipeline.stages.core.stage_base import Stage


class POCGeneratorStage(Stage):
    """
    Automated Proof-of-Concept (POC) Generator.
    Generates standalone Python reproduction scripts for confirmed findings.
    """
    name = "poc_generator"

    def is_enabled(self, context: PipelineContext) -> bool:
        return bool(getattr(context.runtime_config, "enable_poc_generator", True))

    async def run_async(self, context: PipelineContext) -> None:
        findings = [r for r in context.filter_results("finding")]
        confirmed = [f for f in findings if f.get("confidence_label") == "verified" or int(f.get("score", 0)) >= 85]

        if not confirmed:
            context.logger.info("No high-confidence findings found for POC generation")
            return

        poc_dir = context.record.paths.ensure_subdir("pocs")
        generated_count = 0

        for finding in confirmed:
            script_content = self._generate_python_poc(finding)
            if script_content:
                f_type = str(finding.get("finding_type", "vuln"))
                f_hash = hashlib.md5(str(finding.get("url", "")).encode()).hexdigest()[:6]
                filename = f"poc_{f_type}_{f_hash}.py"
                
                poc_path = poc_dir / filename
                poc_path.write_text(script_content, encoding="utf-8")
                generated_count += 1
                
                # Update finding with POC path
                finding["poc_path"] = str(poc_path)
                context.logger.info("Generated POC script: %s", filename)

        context.logger.info("Successfully generated %d POC scripts in %s", generated_count, poc_dir)

    def _generate_python_poc(self, finding: Dict[str, Any]) -> str | None:
        url = finding.get("url")
        if not url: return None
        
        f_type = finding.get("finding_type", "vulnerability")
        desc = finding.get("description", "Reproduction script")
        method = finding.get("method", "GET").upper()
        
        # Try to extract payload from evidence or details
        payload = finding.get("details", {}).get("payload") or finding.get("evidence", {}).get("payload")
        
        # Build headers
        headers = {"User-Agent": "Mozilla/5.0 (ReconnV2 POC Generator)"}
        if "auth" in str(finding.get("tags", [])):
            headers["X-POC-Authenticated"] = "true"

        payload_json = json.dumps(payload) if payload else "None"
        headers_json = json.dumps(headers, indent=8)

        # Template for the Python POC
        template = f'''"""
POC for {f_type}
Description: {desc}
Generated by ReconnV2
"""

import requests
import json
import urllib3

# Suppress insecure request warnings
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

def exploit():
    url = "{url}"
    method = "{method}"
    payload = {payload_json}
    
    print(f"[*] Targeting: {{url}} [{{method}}]")
    
    headers = {headers_json}
    
    try:
        if method == "POST":
            response = requests.post(url, json=payload, headers=headers, verify=False, timeout=15)
        elif method == "PUT":
            response = requests.put(url, json=payload, headers=headers, verify=False, timeout=15)
        else:
            response = requests.get(url, params=payload if method == "GET" else None, headers=headers, verify=False, timeout=15)
        
        print(f"[+] Status Code: {{response.status_code}}")
        print(f"[+] Response Length: {{len(response.text)}}")
        
        if response.status_code < 400:
            print("[+] Potential Success! Review the response manually.")
        else:
            print("[!] Request completed but status code indicates failure ({{response.status_code}}).")
            
    except Exception as e:
        print(f"[-] Error during execution: {{e}}")

if __name__ == "__main__":
    exploit()
'''
        return template
