from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


class HypothesisType(Enum):
    IDOR = "idor"
    SSRF = "ssrf"
    AUTH_BYPASS = "auth_bypass"
    SQLI = "sqli"
    XSS = "xss"
    MASS_ASSIGNMENT = "mass_assignment"


@dataclass
class Hypothesis:
    """A prioritized bug hypothesis generated by the Planner."""
    type: HypothesisType
    target_url: str
    priority: float  # 0.0 to 1.0
    payload_template: Optional[str] = None
    parameters: Dict[str, Any] = field(default_factory=dict)
    identity_requirements: List[str] = field(default_factory=list)  # e.g. ['admin', 'user']
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class Observation:
    """A raw observation collected by the Executor."""
    url: str
    method: str
    status: int
    headers: Dict[str, str]
    body: str
    identity_id: Optional[str] = None
    response_time: float = 0.0
    metadata: Dict[str, Any] = field(default_factory=dict)


class EvidenceLevel(Enum):
    CONFIRMED = "confirmed"
    REJECTED = "rejected"
    INCONCLUSIVE = "needs_more_evidence"


@dataclass
class JudgeResult:
    """The final decision made by the Judge."""
    level: EvidenceLevel
    confidence: float  # 0.0 to 1.0
    reasoning: List[str] = field(default_factory=list)
    finding_data: Optional[Dict[str, Any]] = None
    next_steps: List[str] = field(default_factory=list)
